### PR TITLE
Allow setting any attribute on Slug and TextWithSlug fields. Matches …

### PR DESCRIPTION
**Pull request by eugenequilter**
…the new functionality in Nova 1.1.4 for Text and TextArea Fields. Can be applied via the following:

->withMeta(['extraAttributes' => [
        // 'placeholder' => '0',
        // 'readonly' => true,
        // 'disabled' => true,
        // 'type' => 'number',
        // 'step' => 4,
        // 'required' => true,
    ]]),

### CODE REVIEW

**Comment by benjaminhirsch** [comment]
Looks good, thank you :)

**Comment by mikepmtl** [comment]
I do not understand how to implement this properly.  I can make 'slug' readonly, but it still changes when editing the source field (title field in my case).

The usage I am looking to have is when creating a new resource (a cms document) the slug gets created.  However once it is created, I no longer wish to allow the slug to be modified, when editing the title for instance, because this will invalidate any links to the document that are using the slug for routing.

Is that possible using the withMeta method?

**Comment by eugenequilter** [comment]
withMeta does not provide that functionality. This would have to be a new enhancement.

**Comment by mikepmtl** [comment]
Actually I figured out it will work the way I want simply using the Nova method "hideWhenUpdating()".
Thanks for the quick reply though!  :)

**Pull request merged**
